import type { IProduct, ICategory } from "@/types";

export const MOCK_PRODUCTS: IProduct[] = [
  {
    _id: "1",
    name: "AziRun Pro X1",
    slug: "azirun-pro-x1",
    description: "Premium running shoes with advanced cushioning",
    longDescription: "Experience unparalleled comfort with the AziRun Pro X1. Featuring our revolutionary cushioning technology and breathable mesh upper.",
    price: 149.99,
    salePrice: 119.99,
    stock: 50,
    category: "Running",
    sizes: [
      { size: "US 7", stock: 10 },
      { size: "US 8", stock: 15 },
      { size: "US 9", stock: 12 },
      { size: "US 10", stock: 8 },
      { size: "US 11", stock: 5 },
    ],
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    rating: 4.8,
    reviewCount: 245,
    featured: true,
    isNew: false,
    tags: ["running", "shoes", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    name: "AziForce Court",
    slug: "aziforce-court",
    description: "Classic basketball court shoes",
    longDescription: "Dominate the court with AziForce Court. Designed for peak performance with superior ankle support.",
    price: 179.99,
    stock: 35,
    category: "Basketball",
    sizes: [
      { size: "US 8", stock: 8 },
      { size: "US 9", stock: 10 },
      { size: "US 10", stock: 12 },
      { size: "US 11", stock: 5 },
    ],
    images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
    rating: 4.6,
    reviewCount: 189,
    featured: true,
    isNew: true,
    tags: ["basketball", "shoes", "court"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    name: "AziSlide Comfort",
    slug: "azislide-comfort",
    description: "Ultra-comfortable everyday slides",
    longDescription: "Relax in style with AziSlide Comfort. Perfect for casual wear with memory foam cushioning.",
    price: 59.99,
    salePrice: 44.99,
    stock: 100,
    category: "Casual",
    sizes: [
      { size: "US 7", stock: 25 },
      { size: "US 8", stock: 30 },
      { size: "US 9", stock: 25 },
      { size: "US 10", stock: 20 },
    ],
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400",
    rating: 4.5,
    reviewCount: 312,
    featured: false,
    isNew: false,
    tags: ["casual", "slides", "comfort"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    name: "AziBoost 360",
    slug: "aziboost-360",
    description: "Maximum energy return running shoes",
    longDescription: "Feel the energy with every step. AziBoost 360 features our patented energy-return technology.",
    price: 199.99,
    stock: 25,
    category: "Running",
    sizes: [
      { size: "US 7", stock: 5 },
      { size: "US 8", stock: 8 },
      { size: "US 9", stock: 7 },
      { size: "US 10", stock: 5 },
    ],
    images: ["https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=400",
    rating: 4.9,
    reviewCount: 178,
    featured: true,
    isNew: true,
    tags: ["running", "energy", "premium"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    name: "AziEdge Street",
    slug: "aziedge-street",
    description: "Street-style sneakers for urban explorers",
    longDescription: "Make a statement. AziEdge Street combines bold design with all-day comfort.",
    price: 129.99,
    salePrice: 99.99,
    stock: 45,
    category: "Street",
    sizes: [
      { size: "US 7", stock: 10 },
      { size: "US 8", stock: 12 },
      { size: "US 9", stock: 15 },
      { size: "US 10", stock: 8 },
    ],
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400",
    rating: 4.4,
    reviewCount: 223,
    featured: false,
    isNew: true,
    tags: ["street", "urban", "fashion"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    name: "AziPulse Trail",
    slug: "azipulse-trail",
    description: "Trail running shoes for outdoor adventures",
    longDescription: "Conquer any terrain. AziPulse Trail features aggressive traction and water resistance.",
    price: 159.99,
    stock: 30,
    category: "Trail",
    sizes: [
      { size: "US 8", stock: 8 },
      { size: "US 9", stock: 10 },
      { size: "US 10", stock: 7 },
      { size: "US 11", stock: 5 },
    ],
    images: ["https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400",
    rating: 4.7,
    reviewCount: 156,
    featured: true,
    isNew: false,
    tags: ["trail", "outdoor", "adventure"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "7",
    name: "AziClassic Retro",
    slug: "aziclassic-retro",
    description: "Retro-inspired sneakers for timeless style",
    longDescription: "Classic design meets modern comfort. AziClassic Retro is your everyday favorite.",
    price: 109.99,
    stock: 60,
    category: "Casual",
    sizes: [
      { size: "US 7", stock: 15 },
      { size: "US 8", stock: 18 },
      { size: "US 9", stock: 17 },
      { size: "US 10", stock: 10 },
    ],
    images: ["https://images.unsplash.com/photo-1491553895911-0055uj66ef46?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1491553895911-0055uj66ef46?w=400",
    rating: 4.6,
    reviewCount: 298,
    featured: false,
    isNew: false,
    tags: ["retro", "classic", "casual"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "8",
    name: "AziTrainer Gym",
    slug: "azitrainer-gym",
    description: "High-performance training shoes",
    longDescription: "Built for the gym. AziTrainer Gym provides stability for lifting and flexibility for cardio.",
    price: 139.99,
    salePrice: 119.99,
    stock: 40,
    category: "Training",
    sizes: [
      { size: "US 7", stock: 10 },
      { size: "US 8", stock: 12 },
      { size: "US 9", stock: 10 },
      { size: "US 10", stock: 8 },
    ],
    images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=400",
    rating: 4.5,
    reviewCount: 187,
    featured: true,
    isNew: false,
    tags: ["training", "gym", "fitness"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Running - 4 products
  {
    _id: "9",
    name: "AziRun Elite",
    slug: "azirun-elite",
    description: "Elite marathon running shoes",
    longDescription: "Built for the marathon. AziRun Elite delivers speed and endurance for serious runners.",
    price: 219.99,
    stock: 20,
    category: "Running",
    sizes: [
      { size: "US 7", stock: 5 },
      { size: "US 8", stock: 7 },
      { size: "US 9", stock: 5 },
      { size: "US 10", stock: 3 },
    ],
    images: ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
    rating: 4.8,
    reviewCount: 156,
    featured: false,
    isNew: false,
    tags: ["running", "marathon", "elite"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Basketball - 3 products (need 1 more)
  {
    _id: "10",
    name: "AziSlam Dunk",
    slug: "azislam-dunk",
    description: "High-top basketball sneakers",
    longDescription: "Own the court. AziSlam Dunk features maximum ankle support and explosive cushioning.",
    price: 159.99,
    salePrice: 129.99,
    stock: 28,
    category: "Basketball",
    sizes: [
      { size: "US 8", stock: 7 },
      { size: "US 9", stock: 9 },
      { size: "US 10", stock: 8 },
      { size: "US 11", stock: 4 },
    ],
    images: ["https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=400",
    rating: 4.7,
    reviewCount: 134,
    featured: false,
    isNew: true,
    tags: ["basketball", "high-top", "performance"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Casual - 3 products (need 1 more)
  {
    _id: "11",
    name: "AziComfort Max",
    slug: "azicomfort-max",
    description: "Maximum comfort walking shoes",
    longDescription: "All-day comfort. AziComfort Max features memory foam insoles and breathable design.",
    price: 89.99,
    stock: 55,
    category: "Casual",
    sizes: [
      { size: "US 7", stock: 14 },
      { size: "US 8", stock: 16 },
      { size: "US 9", stock: 15 },
      { size: "US 10", stock: 10 },
    ],
    images: ["https://images.unsplash.com/photo-1520256862855-398228c41684?w=800"],
    thumbnail: "https://images.unsplash.com/photo-1520256862855-398228c41684?w=400",
    rating: 4.4,
    reviewCount: 267,
    featured: false,
    isNew: false,
    tags: ["casual", "walking", "comfort"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_CATEGORIES: ICategory[] = [
  {
    _id: "1",
    name: "Running",
    slug: "running",
    image: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800",
    description: "Premium running shoes for every runner",
    order: 1,
  },
  {
    _id: "2",
    name: "Basketball",
    slug: "basketball",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800",
    description: "Dominate the court with AziMart basketball shoes",
    order: 2,
  },
  {
    _id: "3",
    name: "Casual",
    slug: "casual",
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
    description: "Comfortable everyday shoes for any occasion",
    order: 3,
  },
  {
    _id: "4",
    name: "Street",
    slug: "street",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800",
    description: "Urban street style sneakers",
    order: 4,
  },
  {
    _id: "5",
    name: "Trail",
    slug: "trail",
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800",
    description: "Trail running shoes for outdoor adventures",
    order: 5,
  },
  {
    _id: "6",
    name: "Training",
    slug: "training",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800",
    description: "High-performance training and gym shoes",
    order: 6,
  },
];

export function getFeaturedProducts(): IProduct[] {
  return MOCK_PRODUCTS.filter((p) => p.featured);
}

export function getNewArrivals(): IProduct[] {
  return MOCK_PRODUCTS.filter((p) => p.isNew);
}

export function getProductsByCategory(categorySlug: string): IProduct[] {
  return MOCK_PRODUCTS.filter((p) => {
    const cat = typeof p.category === 'string' ? p.category : p.category.name;
    return cat.toLowerCase() === categorySlug.toLowerCase();
  });
}

export function getProductBySlug(slug: string): IProduct | undefined {
  return MOCK_PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(productId: string): IProduct[] {
  const product = MOCK_PRODUCTS.find((p) => p._id === productId);
  if (!product) return MOCK_PRODUCTS.slice(0, 4);
  return MOCK_PRODUCTS
    .filter((p) => p._id !== productId && p.category === product.category)
    .slice(0, 4);
}
